import type { AnalysisAttempt } from "./analysis.js";
import { CONFIDENCE_METHOD, pairwiseConfidence, type PairwiseConfidence } from "./comparison-confidence.js";
import type { ConditionAssessment } from "./comparison-conditions.js";
import type { AuditSummary } from "./task-audit.js";
export type ComparisonEvidence = { conditions: ConditionAssessment | null; audit: AuditSummary | null; conditions_dataset: string | null; audit_dataset: string | null };
export const escapeEvidence = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
export const pp = (n: number) => `${n > 0 ? "+" : ""}${n.toFixed(1)} pp`;
export const intervalText = (interval: [number, number] | null) => interval ? `${pp(interval[0])} to ${pp(interval[1])}` : "Unavailable: only one task";

export function confidenceRows(pairs: PairwiseConfidence[], baseline: string) {
  return pairs.filter(p => p.left === baseline || p.right === baseline).map(p => {
    const reverse = p.left === baseline;
    const interval: [number, number] | null = p.interval === null ? null : reverse ? [-p.interval[1], -p.interval[0]] : p.interval;
    const difference = reverse ? -p.difference_pp : p.difference_pp;
    return { harness: reverse ? p.right : p.left, difference, interval, difference_text: pp(difference), interval_text: intervalText(interval),
      note: p.interpretation === "insufficient-tasks" ? "More distinct tasks needed" : p.interpretation === "inconclusive" ? "No clear separation" : "Directional in this sample" };
  }).sort((a, b) => b.difference - a.difference || a.harness.localeCompare(b.harness));
}
export function confidenceTable(pairs: PairwiseConfidence[], baseline: string): string {
  return `<table class="confidence-table"><caption>Pass-rate difference from ${escapeEvidence(baseline)}. Positive means more passes.</caption><thead><tr><th scope="col">Harness</th><th scope="col">Observed difference</th><th scope="col">Exploratory 95% interval</th></tr></thead><tbody>${confidenceRows(pairs, baseline).map(r => `<tr><th scope="row">${escapeEvidence(r.harness)}</th><td>${r.difference_text}</td><td>${r.interval_text}<small>${r.note}</small></td></tr>`).join("")}</tbody></table>`;
}
export function evidenceHtml(evidence: ComparisonEvidence): string {
  const c = evidence.conditions; const a = evidence.audit;
  const source = "https://github.com/Tom910/agent-overhead-bench/tree/main/evidence/";
  return `${c ? `<section id="comparison-conditions" class="evidence-section"><h2>Are the conditions matched?</h2><p>${c.controlled_comparison ? "Recorded controls match." : "Partly. This campaign supports an observed comparison, not a fully controlled harness experiment."} ${c.attempts_validated} selected run identities validated.</p><div class="conditions-grid">${c.checks.map(check => `<details><summary><span>${escapeEvidence(check.label)}</span><strong class="condition-status ${check.status}">${check.status === "unknown" ? "Not recorded" : check.status === "different" ? "Different" : check.status === "recorded" ? "Recorded" : "Matched"}</strong></summary><p>${escapeEvidence(check.detail)}</p></details>`).join("")}</div><p><a href="${source}${escapeEvidence(evidence.conditions_dataset!)}/conditions.json">Inspect the condition manifest ↗</a></p></section>` : ""}
${a ? `<section id="verification-audit" class="evidence-section"><h2>What changed in verification?</h2><p><strong>${a.changes.length} Textual attempts change from fail to pass</strong> under class-based event listeners. These are a separate audit revision; the headline chart and table retain original campaign outcomes.</p><p>Replayed ${a.reproduced} original-image attempts: all reproduced their historical grades. Applied corrected Textual verification to ${a.corrected} of 25 attempts. ${a.unavailable} of ${a.audited} audited attempts could not be replayed because their exact original images were unavailable.</p><ul>${a.changes.map(r => `<li>${escapeEvidence(r.harness)} · repetition ${r.rep + 1} (stored index ${r.rep}) · ${r.original === 1 ? "pass" : "fail"} → ${r.corrected === 1 ? "pass" : "fail"}</li>`).join("")}</ul><p>SuperJSON and Ink prompts are clarified for future runs; old agents did not receive those clarifications. One Hermes Ink failure is attributed to session storage. Its cost and unsuccessful end-to-end outcome remain included.</p><p>Recovered post-verification workspaces reproduced original grades; original temporary patch files did not survive. Reference solutions pass, and an event-suppression negative control still fails.</p><p><a href="${source}${escapeEvidence(evidence.audit_dataset!)}/README.md">Read the separate verification revision ↗</a> · <a href="data/task-audit.json">Download audit data</a></p></section>` : ""}`;
}
export function comparisonMarkdown(attempts: readonly AnalysisAttempt[], evidence: ComparisonEvidence): string {
  const pairs = pairwiseConfidence(attempts);
  return `\n## How convincing are the differences?\n\nOriginal campaign verification; observed differences, not a general harness ranking.\n\n| Comparison (left − right) | Pass-rate difference | Exploratory 95% interval | Task clusters |\n|---|---:|---|---:|\n${pairs.map(p => `| ${escapeEvidence(p.left)} − ${escapeEvidence(p.right)} | ${pp(p.difference_pp)} | ${intervalText(p.interval)} | ${p.tasks} |`).join("\n")}\n\n${CONFIDENCE_METHOD}\n\n“Best = 100%” is an observed relative index, not statistical certainty.\n${evidence.conditions ? `\n## Comparison conditions\n\n${evidence.conditions.controlled_comparison ? "Recorded controls match." : "Not a fully controlled comparison: missing controls and image differences remain."}\n\n| Condition | Evidence |\n|---|---|\n${evidence.conditions.checks.map(c => `| ${c.label} | ${c.status} |`).join("\n")}\n\n[Condition manifest](../${evidence.conditions_dataset}/conditions.json)\n` : ""}${evidence.audit ? `\n## Separate verification revision\n\n${evidence.audit.changes.length} Textual attempts change from fail to pass under the corrected verifier; original headline results remain unchanged. ${evidence.audit.reproduced}/${evidence.audit.audited} original-image replays reproduce historical grades; ${evidence.audit.corrected}/25 Textual attempts have corrected replays. Original temporary patches were unavailable; effective patches were recovered from retained post-verification workspaces.\n\n[Audit, limitations and reproduction](../${evidence.audit_dataset}/README.md)\n` : ""}`;
}
