import {createServer} from 'node:http';
import {once} from 'node:events';
import {spawn} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {register} from 'node:module';
import assert from 'node:assert/strict';
register('/repo/scripts/ts-source-loader.mjs',import.meta.url);
const {startProxy}=await import('/repo/packages/proxy/src/proxy.ts');
const root='/proof/results';mkdirSync(root,{recursive:true,mode:0o700});mkdirSync(root+'/auth',{mode:0o700});
const capability='fixtureCapability012345678901234567890123456789';const bearer='synthetic-oauth-access-only';let current='';const observed=[];
const upstream=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);observed.push({case:current,path:req.url,authorization_matches:req.headers.authorization==='Bearer '+bearer,account_matches:req.headers['chatgpt-account-id']==='synthetic-account',capability_stripped:req.headers['x-aob-proxy-token']===undefined,model:body.model,reasoning:body.reasoning,parallel:body.parallel_tool_calls,store:body.store,input_types:(body.input??[]).map(x=>x.type),tool_calls:(body.input??[]).filter(x=>x.type==='function_call').map(x=>({name:x.name,call_id:x.call_id,arguments:x.arguments})),tool_results:(body.input??[]).filter(x=>x.type==='function_call_output').map(x=>({call_id:x.call_id,output:x.output})),has_previous_response_id:'previous_response_id' in body,has_conversation:'conversation' in body});if(current==='unauthorized'){res.writeHead(401,{'content-type':'application/json'});res.end(JSON.stringify({error:{message:'synthetic rejection'}}));return;}res.writeHead(200,{'content-type':'text/event-stream'});const emit=o=>res.write('data: '+JSON.stringify(o)+'\n\n');emit({type:'response.created',response:{id:'r',model:'gpt-6-luna',status:'in_progress'}});const model=current==='terminal-mismatch'?'wrong-served-model':current==='terminal-missing'?undefined:'gpt-6-luna';emit({type:'response.completed',response:{id:'r',object:'response',status:'completed',...(model===undefined?{}:{model}),output:[{id:'m',type:'message',role:'assistant',content:[{type:'output_text',text:'fixture complete',annotations:[]}]}],usage:{input_tokens:100,output_tokens:30,total_tokens:130,input_tokens_details:{cached_tokens:40},output_tokens_details:{reasoning_tokens:10}}}});res.end();});
upstream.listen(0,'127.0.0.1');await once(upstream,'listening');
const meter=await startProxy({run_id:'offline-oauth-meter-proof',upstream:'http://127.0.0.1:'+upstream.address().port,outPath:root+'/events.jsonl',host:'127.0.0.1',authToken:capability,expectedModel:'gpt-6-luna',maxModelRequests:10});
const auth={type:'codex',access_token:bearer,refresh_token:'',account_id:'synthetic-account',expired:'2099-01-01T00:00:00Z',last_refresh:new Date().toISOString(),aob_disable_unauthorized_replay:true,aob_meter_base_url:meter.baseUrl,headers:{'x-aob-proxy-token':capability}};
writeFileSync(root+'/auth/codex.json',JSON.stringify(auth),{mode:0o600});
const config={host:'127.0.0.1',port:8317,'auth-dir':root+'/auth','api-keys':['synthetic-bridge-key'],'commercial-mode':true,'request-log':false,debug:false,'logging-to-file':false,'proxy-url':'direct','request-retry':0,'max-retry-credentials':1,'max-retry-interval':0,streaming:{'bootstrap-retries':0},'remote-management':{'secret-key':'','disable-control-panel':true,'disable-auto-update-panel':true},plugins:{enabled:false},discovery:{enabled:false},pprof:{enable:false},'quota-exceeded':{'switch-project':false,'switch-preview-model':false},'disable-image-generation':'passthrough',codex:{'disable-codex-cloaking':true,'identity-confuse':false,'stream-bootstrap-buffering':false,'optimize-multi-agent-v2':false}};
config.payload={override:[{models:[{name:'gpt-6-luna',protocol:'codex'}],params:{'reasoning.effort':'low',store:false}}],filter:[{models:[{name:'gpt-6-luna',protocol:'codex'}],params:['input.#(type=="reasoning")#','previous_response_id','conversation']}]};
writeFileSync(root+'/config.json',JSON.stringify(config),{mode:0o600});
const child=spawn('/bridge',['-config',root+'/config.json'],{cwd:root,env:{PATH:'/usr/local/bin:/usr/bin:/bin'},stdio:['ignore','pipe','pipe']});let logs='';child.stdout.on('data',c=>logs+=c);child.stderr.on('data',c=>logs+=c);
const outcomes=[];
try{let ready=false;for(let i=0;i<100;i++){try{const r=await fetch('http://127.0.0.1:8317/v1/models',{headers:{authorization:'Bearer synthetic-bridge-key'}});if(r.ok){const listing=await r.json();writeFileSync(root+'/model-ids.json',JSON.stringify((listing.data??[]).map(x=>x.id)));if((listing.data??[]).some(x=>x.id==='gpt-6-luna')){ready=true;break}}}catch{}await new Promise(r=>setTimeout(r,50));}assert(ready,'bridge startup');
for(const [name,wire,model] of [['normal-chat','chat','gpt-6-luna'],['normal-chat-nonstream','chat','gpt-6-luna'],['normal-responses','responses','gpt-6-luna'],['normal-responses-nonstream','responses','gpt-6-luna'],['terminal-mismatch','chat','gpt-6-luna'],['terminal-missing','responses','gpt-6-luna'],['requested-wrong','chat','gpt-6-astra'],['unauthorized','responses','gpt-6-luna']]){current=name;const encrypted=Buffer.from([128,...Array(8).fill(0),...Array.from({length:64},(_,i)=>i+9)]).toString('base64url');const stream=!name.endsWith('nonstream');const body=wire==='chat'?{model,messages:[{role:'user',content:'fixture'},{role:'assistant',content:null,reasoning_details:[{type:'reasoning.encrypted',data:encrypted}],tool_calls:[{id:'call_fixture',type:'function',function:{name:'probe',arguments:'{}'}}]},{role:'tool',tool_call_id:'call_fixture',content:'synthetic-result'},{role:'assistant',content:'continue'}],tools:[{type:'function',function:{name:'probe',parameters:{type:'object',properties:{}}}}],stream,reasoning_effort:'high'}:{model,input:[{type:'message',role:'user',content:'fixture'},{type:'reasoning',id:'rs_first',encrypted_content:encrypted,summary:[]},{type:'function_call',call_id:'call_fixture',name:'probe',arguments:'{}'},{type:'function_call_output',call_id:'call_fixture',output:'synthetic-result'},{type:'reasoning',id:'rs_second',encrypted_content:encrypted,summary:[]},{type:'message',role:'assistant',content:'continue'}],tools:[{type:'function',name:'probe',parameters:{type:'object',properties:{}}}],stream,reasoning:{effort:'high'},previous_response_id:'resp_synthetic',conversation:'conv_synthetic'};const before=observed.length;const response=await fetch('http://127.0.0.1:8317/v1/'+(wire==='chat'?'chat/completions':'responses'),{method:'POST',headers:{authorization:'Bearer synthetic-bridge-key','content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const responseText=await response.text();writeFileSync(root+'/'+name+'-client.txt',responseText,{mode:0o600});await meter.flush();outcomes.push({case:name,client_status:response.status,actual_backend_attempts:observed.length-before});}
}finally{child.kill('SIGTERM');await Promise.race([once(child,'exit'),new Promise(r=>setTimeout(r,3000))]);if(child.exitCode===null)child.kill('SIGKILL');await meter.close();await new Promise(r=>upstream.close(r));writeFileSync(root+'/bridge-private.log',logs,{mode:0o600});}
writeFileSync(root+'/outcomes.json',JSON.stringify(outcomes));
const events=readFileSync(root+'/events.jsonl','utf8').trim().split('\n').map(JSON.parse);const side=readFileSync(root+'/events.jsonl.upstream.jsonl','utf8').trim().split('\n').map(JSON.parse);
assert.equal(observed.length,7);assert(observed.every(x=>x.authorization_matches&&x.account_matches&&x.capability_stripped));assert.equal(outcomes.find(x=>x.case==='requested-wrong').actual_backend_attempts,0);assert.equal(outcomes.find(x=>x.case==='unauthorized').actual_backend_attempts,1);
const success=events.filter(e=>e.status===200);assert.equal(success.length,6);assert(success.slice(0,4).every(e=>e.model_served==='gpt-6-luna'));assert.equal(success[4].model_served,null);assert.equal(success[5].model_served,null);assert(success.every(e=>e.usage.input===100&&e.usage.cached_input===40&&e.usage.output===30&&e.usage.reasoning_output===10));
for(const x of observed){assert.equal(x.reasoning.effort,'low');assert.equal(x.store,false);assert.deepEqual(x.input_types,['message','function_call','function_call_output','message']);assert.equal(x.tool_calls[0].name,'probe');assert.equal(x.tool_calls[0].call_id,'call_fixture');assert.equal(x.tool_results[0].call_id,'call_fixture');assert.equal(x.tool_results[0].output,'synthetic-result');assert(!x.has_previous_response_id&&!x.has_conversation)}
const allEvidence=readFileSync(root+'/events.jsonl','utf8')+readFileSync(root+'/events.jsonl.upstream.jsonl','utf8');assert(!allEvidence.includes(bearer)&&!allEvidence.includes(capability));
const result={kind:'offline-synthetic-oauth-bridge-c1-backend',real_account_verified:false,network:'Docker --network none; all service endpoints loopback',outcomes,backend:observed,c1:events.map(e=>({seq:e.seq,path:e.path,status:e.status,model_requested:e.model_requested,model_served:e.model_served,usage:e.usage,error:e.error})),conditions:side.map(e=>e.request_conditions)};writeFileSync(root+'/summary.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({actual_backend_attempts:observed.length,c1_events:events.length,oauth_header_preservation:true,capability_stripped:true,terminal_identity_fail_closed:true,wrong_model_backend_attempts:0,unauthorized_backend_attempts:1}));
